name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags: 
      - v[1-9]+.[0-9]

jobs:
  git-tag:
    runs-on: [self-hosted]
    outputs:
      tag_name: ${{ steps.vars.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Set output
        id: vars
        run: echo ::set-output name=TAG_NAME::$(git describe)

  build-rpi3-dmx-32bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM, rpios32, dmx]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI3-DMX 32-bit
      run: make -j4 PLATFORM=rpi3
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi3-dmx-32bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi3-sdl2-32bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM, rpios32]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI3-SDL2 32-bit
      run: make -j4 PLATFORM=rpi3-sdl2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi3-sdl2-32bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-dmx-32bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM, rpios32, dmx]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI4-DMX 32-bit
      run: make -j4 PLATFORM=rpi4
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-dmx-32bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-sdl2-32bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM, rpios32]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI4-SDL2 32-bit
      run: make -j4 PLATFORM=rpi4-sdl2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-sdl2-32bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi3-dmx-64bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, rpios64, dmx]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI3-DMX 64-bit
      run: make -j4 PLATFORM=rpi3-64-dmx
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi3-dmx-64bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi3-sdl2-64bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, rpios64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI3-SDL2 64-bit
      run: make -j4 PLATFORM=rpi3-64-sdl2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi3-sdl2-64bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-dmx-64bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, rpios64, dmx]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI4-DMX 64-bit
      run: make -j4 PLATFORM=rpi4-64-dmx
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-dmx-64bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-sdl2-64bit-rpios:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, rpios64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RPIOS RPI4-SDL2 64-bit
      run: make -j4 PLATFORM=rpi4-64-sdl2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-sdl2-64bit-rpios
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-dmx-64bit-manjaro:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, manjaro]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for Manjaro RPI4-DMX 64-bit
      run: make -j4 PLATFORM=rpi4-64-dmx
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-dmx-64bit-manjaro
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**

  build-rpi4-sdl2-64bit-manjaro:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, manjaro]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for Manjaro RPI4-SDL2 64-bit
      run: make -j4 PLATFORM=rpi4-64-sdl2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry-${{ needs.git-tag.outputs.tag_name }}-rpi4-sdl2-64bit-manjaro
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**
          
  build-RK3399-sdl2-64bit-manjaro:
    needs: git-tag
    runs-on: [self-hosted, Linux, ARM64, rockpro64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make capsimg
      run: make capsimg
    - name: make for RK3399
      run: make -j4 PLATFORM=n2
    - uses: actions/upload-artifact@v3
      with:
        name: amiberry--${{ needs.git-tag.outputs.tag_name }}-rk3399-sdl2-64bit-manjaro
        path: |
          amiberry
          capsimg.so
          abr/**
          conf/**
          controllers/**
          data/**
          kickstarts/**
          savestates/**
          screenshots/**
          whdboot/**
    
