# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: RPI-32

jobs:
- job: Build
  strategy:
    matrix:
      RPI4-DMX:
        platform: 'rpi4'
      RPI4-SDL2:
        platform: 'rpi4-sdl2'
      RPI3-DMX:
        platform: 'rpi3'
      RPI3-SDL2:
        platform: 'rpi3-sdl2'
      RPI2-DMX:
        platform: 'rpi2'
      RPI2-SDL2:
        platform: 'rpi2-sdl2'
      RPI1-DMX:
        platform: 'rpi1'
      RPI1-SDL2:
        platform: 'rpi1-sdl2'

  steps:
  - script: make -j4 PLATFORM=$(platform)
    displayName: 'Compile $(platform) target'
