# RK3399, SDL2, 64-bit
steps:
  - checkout: self
    submodules: true
    clean: true
  
  - script: VERSION_TAG=`git describe --abbrev=0` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    displayName: Set the tag name as an environment variable

  - script: |
      cd external/capsimg
      ./bootstrap.fs
      ./configure.fs
      make -f Makefile.fs
      cp capsimg.so $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      cd external/FloppyDriveBridge
      make
      cp FloppyBridge.so $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      make -j4 PLATFORM=n2
      mkdir amiberry-RK3399-sdl2-64bit
    displayName: 'Compile for RK3399 SDL2 64-bit'
  
  - task: CopyFiles@2
    inputs:
     Contents: |
        amiberry
        capsimg.so
        FloppyBridge.so
        abr/**
        conf/**
        controllers/**
        data/**
        kickstarts/**
        savestates/**
        screenshots/**
        whdboot/**
     TargetFolder: amiberry-RK3399-sdl2-64bit
  
  - task: ArchiveFiles@2
    displayName: 'Archive RK3399_release'
    inputs:
      rootFolderOrFile: 'amiberry-RK3399-sdl2-64bit'
      includeRootFolder: true
      archiveFile: '$(Build.ArtifactStagingDirectory)/amiberry-$(VERSION_TAG)-rk3399-sdl2-64bit-manjaro.zip'

  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: $(Build.ArtifactStagingDirectory)
     ArtifactName: RK3399_sdl2_release