# RPI3, Dispmanx, 32-bit
steps:
  - checkout: self
    submodules: true
  - script: make -j4 PLATFORM=rpi3
    displayName: 'Compile for RPI3 (Dispmanx) 32-bit'
  
  - task: CopyFiles@2
    inputs:
     Contents: amiberry
     TargetFolder: $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: $(Build.ArtifactStagingDirectory)
     ArtifactName: rpi3_dmx_release