# RPI3, DMX, 64-bit
steps:
  - checkout: self
    submodules: true
    clean: true
  
  - script: VERSION_TAG=`git describe --abbrev=0` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    displayName: Set the tag name as an environment variable

  - script: |
      cd external/capsimg
      ./bootstrap.fs
      ./configure.fs
      make -f Makefile.fs
      cp capsimg.so $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      cd external/FloppyDriveBridge
      make
      cp FloppyBridge.so $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      make -j4 PLATFORM=rpi3-64-dmx
      mkdir amiberry-rpi3-dmx-64bit
    displayName: 'Compile for RPI3 DMX 64-bit'
  
  - task: CopyFiles@2
    inputs:
     Contents: |
        amiberry
        capsimg.so
        FloppyBridge.so
        abr/**
        conf/**
        controllers/**
        data/**
        kickstarts/**
        savestates/**
        screenshots/**
        whdboot/**
     TargetFolder: amiberry-rpi3-dmx-64bit
  
  - task: ArchiveFiles@2
    displayName: 'Archive rpi3-64-dmx_release'
    inputs:
      rootFolderOrFile: 'amiberry-rpi3-dmx-64bit'
      includeRootFolder: true
      archiveFile: '$(Build.ArtifactStagingDirectory)/amiberry-$(VERSION_TAG)-rpi3-dmx-64bit.zip'

  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: $(Build.ArtifactStagingDirectory)
     ArtifactName: rpi3-64-dmx_release